DROP FULLTEXT INDEX ON [dbo].[tbl_Customer]

ALTER TABLE [dbo].[tbl_Customer]
ALTER COLUMN [CustomerName] NVARCHAR(100) NULL

ALTER TABLE [dbo].[tbl_Customer]
ALTER COLUMN [Nick] NVARCHAR(100) NULL

CREATE NONCLUSTERED INDEX [ID_tbl_Customer_Name] ON [dbo].[tbl_Customer]
(
	[CustomerName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [ID_tbl_Customer_Nick] ON [dbo].[tbl_Customer]
(
	[Nick] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO