//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupOrder()
        {
            this.DeliverySaveNotifications = new HashSet<DeliverySaveNotification>();
            this.JtExpressOrders = new HashSet<JtExpressOrder>();
            this.tbl_Order = new HashSet<tbl_Order>();
        }
    
        public string Code { get; set; }
        public int CustomerId { get; set; }
        public long DeliveryAddressId { get; set; }
        public int OrderStatusId { get; set; }
        public int PaymentStatusId { get; set; }
        public int PaymentMethodId { get; set; }
        public int DeliveryMethodId { get; set; }
        public string ShippingCode { get; set; }
        public decimal ShippingFee { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public double Weight { get; set; }
        public decimal Cod { get; set; }
        public Nullable<int> TransportId { get; set; }
        public Nullable<int> TransportBranchId { get; set; }
        public Nullable<int> PostalDeliveryMethodId { get; set; }
    
        public virtual DeliveryAddress DeliveryAddress { get; set; }
        public virtual DeliveryMethod DeliveryMethod { get; set; }
        public virtual OrderStatu OrderStatu { get; set; }
        public virtual tbl_Customer tbl_Customer { get; set; }
        public virtual tbl_TransportCompany tbl_TransportCompany { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliverySaveNotification> DeliverySaveNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JtExpressOrder> JtExpressOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Order> tbl_Order { get; set; }
    }
}
