//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JtExpressOrder
    {
        public Nullable<int> OrderId { get; set; }
        public string Code { get; set; }
        public string SenderName { get; set; }
        public string SenderPhone { get; set; }
        public string SenderAddress { get; set; }
        public string SenderProvince { get; set; }
        public string SenderDistrict { get; set; }
        public string SenderWard { get; set; }
        public string ReceiverName { get; set; }
        public string ReceiverPhone { get; set; }
        public string ReceiverAddress { get; set; }
        public string ReceiverProvince { get; set; }
        public string ReceiverDistrict { get; set; }
        public string ReceiverWard { get; set; }
        public string PostalCode { get; set; }
        public string PostalBranchCode { get; set; }
        public decimal Fee { get; set; }
        public decimal InsuranceFee { get; set; }
        public decimal Cod { get; set; }
        public decimal CodFee { get; set; }
        public string ItemName { get; set; }
        public int ItemNumber { get; set; }
        public double Weight { get; set; }
        public string Note { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string GroupOrderCode { get; set; }
    
        public virtual GroupOrder GroupOrder { get; set; }
        public virtual tbl_Order tbl_Order { get; set; }
    }
}
