//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IM_PJ.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Config
    {
        public int ID { get; set; }
        public Nullable<double> NumOfDateToChangeProduct { get; set; }
        public Nullable<double> NumOfProductCanChange { get; set; }
        public Nullable<double> FeeChangeProduct { get; set; }
        public Nullable<double> FeeDiscountPerProduct { get; set; }
        public string ChangeGoodsRule { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string SecurityCode { get; set; }
        public string RetailReturnRule { get; set; }
        public string CSSPrintBarcode { get; set; }
        public Nullable<int> HideProduct { get; set; }
        public Nullable<int> ViewAllOrders { get; set; }
        public Nullable<int> ViewAllReports { get; set; }
        public int MinQuantityOfOrder { get; set; }
        public int StaffIndex { get; set; }
        public string WPNewsClothes { get; set; }
        public string WPNewsCosmetics { get; set; }
        public string WPZaloClothes { get; set; }
        public string WPZaloCosmetics { get; set; }
        public string WPFBClothes { get; set; }
        public string WPFBCosmetics { get; set; }
        public string WPHotlineClothes { get; set; }
        public string WPHotlineCosmetics { get; set; }
        public string WPImageClothes { get; set; }
        public string WPImageCosmetics { get; set; }
        public string WPNewsLixi { get; set; }
        public string WPHotlineLixi { get; set; }
        public string WPZaloLixi { get; set; }
        public string WPCategoryCosmetics { get; set; }
        public string WPCategoryPerfume { get; set; }
        public string WPVideoClothes { get; set; }
        public string WPVideoCosmetics { get; set; }
        public string WPBannerTop { get; set; }
        public string WPBannerProduct { get; set; }
        public string WPTime { get; set; }
    }
}
